// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"bsFilters","status":true,"description":"","parameters":{}},
{"name":"tupWorldChoice","status":true,"description":"Allows dynamic multiple choices in multiple formats","parameters":{}}
];
