// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"bsFilters","status":false,"description":"","parameters":{}},
{"name":"tupWorldChoice","status":false,"description":"Allows dynamic multiple choices in multiple formats","parameters":{}},
{"name":"funUiThing","status":false,"description":"","parameters":{}},
{"name":"renkaiThing","status":false,"description":"","parameters":{}},
{"name":"S.RMMZ","status":false,"description":"","parameters":{}},
{"name":"hwStyleBars","status":false,"description":"","parameters":{}},
{"name":"HWFireworks","status":true,"description":"","parameters":{}}
];
